# Generated by Django 3.0.1 on 2019-12-28 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristiques',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('niveau', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('attaque', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('vitesse', models.IntegerField()),
                ('precision', models.IntegerField()),
                ('effet', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('casque', models.IntegerField()),
                ('armure', models.IntegerField()),
                ('pantalon', models.IntegerField()),
                ('chaussures', models.IntegerField()),
                ('arme', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('pd', models.IntegerField()),
                ('pa', models.IntegerField()),
                ('typeobjet', models.IntegerField()),
                ('prix_achat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('objet0', models.IntegerField()),
                ('objet1', models.IntegerField()),
                ('objet2', models.IntegerField()),
                ('objet3', models.IntegerField()),
                ('objet4', models.IntegerField()),
                ('objet5', models.IntegerField()),
                ('dateupdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.IntegerField()),
                ('idjoueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
