# Generated by Django 3.0.3 on 2020-03-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='prix_vente',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
