# Generated by Django 3.0.3 on 2020-03-10 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristiques',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('niveau', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('attaque', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('vitesse', models.IntegerField()),
                ('precision', models.IntegerField()),
                ('effet', models.IntegerField()),
                ('last_attack', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('casque', models.IntegerField()),
                ('armure', models.IntegerField()),
                ('pantalon', models.IntegerField()),
                ('chaussures', models.IntegerField()),
                ('arme', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_module', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('pd', models.IntegerField()),
                ('pa', models.IntegerField()),
                ('typeobjet', models.IntegerField()),
                ('prix_achat', models.IntegerField()),
                ('prix_vente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('objet0', models.IntegerField()),
                ('objet1', models.IntegerField()),
                ('objet2', models.IntegerField()),
                ('objet3', models.IntegerField()),
                ('objet4', models.IntegerField()),
                ('objet5', models.IntegerField()),
                ('dateupdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Prof_TP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteweb.Module')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteweb.Prof')),
            ],
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.IntegerField()),
                ('idjoueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant_TP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nom_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteweb.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Competence_Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_competence', models.TextField()),
                ('nombre_exp_gagne', models.IntegerField()),
                ('valide', models.BooleanField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nom_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteweb.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Combat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_obtenu', models.IntegerField()),
                ('date_attaque', models.DateTimeField()),
                ('gagnant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joueur_gagnant', to=settings.AUTH_USER_MODEL)),
                ('joueur_attaque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joueur_attaque', to=settings.AUTH_USER_MODEL)),
                ('joueur_defense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joueur_defense', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
