# Generated by Django 3.0.4 on 2020-03-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristiques',
            name='exp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
